# 	arrivalRate: Constant rate (X users/second)
# 	arrivalCount: Total users distributed over duration
# https://www.artillery.io/docs/reference/test-script#load-phase-examples

config:
  target: 'http://host.docker.internal:3001'
  phases:
    - arrivalRate: 20
      duration: 10
      name: "20 users/second for 10 seconds"
    - arrivalRate: 20
      rampTo: 1000
      duration: 10
      name: "20 users/second to 1000 users/second for 10 seconds"
    - arrivalCount: 1000
      duration: 10
      name: "1000 users for 10 seconds"
  environments:
    localhost:
      target: 'http://localhost:3001'
    indocker:
      target: 'http://host.docker.internal:3001'
    production:
      target: 'https://quiz.wetsnow.com'
  defaults:
    headers:
      Content-Type: 'application/json'
      Accept: 'application/json'
  plugins:
    expect:
      outputFormat: silent
    fuzzer:
      outputFormat: silent
