
# 	arrivalRate: Constant rate (X users/second)
# 	arrivalCount: Total users distributed over duration
# https://www.artillery.io/docs/reference/test-script#load-phase-examples

config:
  target: 'http://host.docker.internal:3001'
  phases:
    - arrivalRate: 2
      duration: 10
      name: "2 users/second for 10 seconds"
  environments:
    localhost:
      target: 'http://localhost:3001'
    indocker:
      target: 'http://host.docker.internal:3001'
    production:
      target: 'https://quiz.wetsnow.com'
  defaults:
    headers:
      Content-Type: 'application/json'
      Accept: 'application/json'
    environment: 'indocker'
  processor: './processors.ts'
  plugins:
    expect:
      outputFormat: silent
