name: Deploy

on:
  workflow_dispatch: # Allow manual trigger
#   workflow_run:
#     workflows: ["Release"]
#     types:
#       - completed

# Cancel any in-progress deployment for the same ref if a new one starts
# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

jobs:
  deploy:
    # Ensure we only run when Release completed successfully
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Deploy to production via SSH and restart services
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.PROD_SERVER_HOST }}
          username: ${{ vars.PROD_SERVER_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          # Optional: specify a non-default SSH port via repository variable `PROD_SERVER_PORT`.
          # If the variable is unset, the appleboy/ssh-action will default to port 22.
          port: ${{ vars.PROD_SERVER_PORT }}
          script: |
            # appleboy/ssh-action executes this in the login shell configured for the
            # remote user (fish on our prod host). The standard Bash `set -euo pipefail`
            # flags are not understood by fish, so we avoid them here.
            cd ~/src/quiz
            echo "Running \`task restart-prod\` in $(pwd) on $HOSTNAME ..."
            task restart-prod
