name: Test on Merge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual trigger

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create .env from secret
      run: |
        if [ -n "$DOT_ENV_FILE_FOR_API_TESTS" ]; then
          echo "Writing .env from DOT_ENV_FILE_FOR_API_TESTS secret..."
          printf '%s\n' "$DOT_ENV_FILE_FOR_API_TESTS" > .env
          ls -la .env
        else
          echo "DOT_ENV_CONTENTS secret is empty or not set; skipping .env creation."
        fi
      env:
        DOT_ENV_FILE_FOR_API_TESTS: ${{ secrets.DOT_ENV_FILE_FOR_API_TESTS }}

    - name: Setup Environment
      uses: ./.github/actions/setup-environment
      with:
        enable-docker: 'true'

    - name: Run Tests
      uses: ./.github/actions/run-tests

    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          test-results/
          backend/coverage*.out
          frontend/coverage/
          zap/reports/
        retention-days: 7

    - name: Clean up test environment
      if: always()
      run: |
        echo "Cleaning up test environment..."

        # Stop test servers and clean up
        task stop-test-servers || true
        task clean-test || true

        # Clean up Docker
        docker system prune -f || true

    # Provide an SSH debugging session if the workflow fails so a developer can connect.
    # The session will automatically end after 5 minutes if nobody connects.
    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 5
